### ISSUE TITLE
CSS transitions janky in Graphene

### ISSUE THREAD

**Issue by gordonbrander** [mozilla/browser.html#202]
While implementing the dashboard, I noticed that CSS animations are slow and janky in Graphene. Here's the relevant CSS from the dashboard:

```css
.tile-large .tile-thumbnail {
  background: #fff;
  background-size: cover;
  border-radius: 12px;
  height: 100px;
  transition: transform 80ms ease-out;
  width: 160px;
}

.tile-large:hover .tile-thumbnail {
  transform: scale(1.1);
}
```

No JavaScript involved in this animation at all. The transition duration is short, but has no jank in Firefox Desktop. It is always janky in Graphene. Additionally, the background image in `.tile-thumbnail` will occasionally flicker in Graphene during or after the transition. This never happens on Desktop.

cc @paulrouget
